apiVersion: v1
kind: Service
metadata:
  name: {{ template "deck.name" . }}
{{- if .Values.deck.service.annotations }}
  annotations:
{{ toYaml .Values.deck.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.deck.service.type }}
  selector:
    app: {{ template "deck.name" . }}
  ports:
  - port: {{ .Values.deck.service.externalPort }}
    targetPort: {{ .Values.deck.service.internalPort }}
    protocol: TCP
    name: http