apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
  labels:
    app: {{ template "prow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:  
  hmac: {{ default "" .Values.hmacToken | b64enc | quote }}
