apiVersion: v1
kind: Secret
metadata:
  name: oauth-token
  labels:
    app: {{ template "prow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:  
  oauth: {{ default "" .Values.oauthToken | b64enc | quote }}
