apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "pipeline.name" . }}
  labels:
    app: {{ template "pipeline.name" . }}
spec:
  replicas: {{ .Values.pipeline.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
{{- if .Values.pipeline.datadog.enabled }}
      annotations:
        ad.datadoghq.com/pipeline.logs: '[{"source":"prow","service":"pipeline"}]'
{{- end }}
      labels:
        app: {{ template "pipeline.name" . }}
    spec:
      serviceAccountName: {{ template "pipeline.name" . }}
      terminationGracePeriodSeconds: {{ .Values.pipeline.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "pipeline.name" . }}
        args:
        - --tot-url
        - http://buildnum
        - --config
        - /etc/config/config.yaml
        image: {{ tpl .Values.pipeline.image.repository . }}:{{ tpl .Values.pipeline.image.tag . }}
        imagePullPolicy: {{ .Values.pipeline.imagePullPolicy }}
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.pipeline.resources | indent 10 }}
    {{- with .Values.pipeline.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pipeline.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pipeline.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: config
        name: config
